name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          extensions: sqlite, pdo_sqlite

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: --no-interaction --prefer-dist

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node dependencies
        run: npm ci --no-audit --no-fund

      - name: Build assets
        run: npm run build

      - name: Prepare app environment
        run: |
          cp .env.example .env || true
          php artisan key:generate --force

      - name: Run tests (Pest)
        run: vendor/bin/pest --ci --colors=always


